# Generated by Django 2.2 on 2020-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSong', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
